
services:
#--------------------------------------------------------------------------------

 # PostgreSQL database service.
  postgres:                                     # Defines a service named "postgres"
    image: postgres:16                          # Uses the Docker image of PostgreSQL version 16
    container_name: postgres-db                 # Names the container as "postgres-db"
    restart: always                             # Configures the container to always restart when it stops

    env_file:
      - .env                                    # Loads environment variables from the .env file

    ports:
      - "5432:5432"                             # Maps port 5432 of the host to port 5432 of the container

    volumes:
      - postgres_data:/var/lib/postgresql/data  # Mounts a volume to persist PostgreSQL data


  # puppies_api application.
  puppies:                                       # Defines the application service.
    build: .                                     # Builds the Dockerfile in the current directory.

    ports:
      - "8081:8080"

    depends_on:                                  # This service depends on the postgres service.
      - postgres

volumes:
  postgres_data:                                 # Defines a volume named "postgres_data" for data persistence

#--------------------------------------------------------------------------------